### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#47]
Before open sourcing, we need to tackle these tasks
- [ ] Reset fastlanebot ci API Token
- [x] Reset taquitos ci API Token
- [x] Update architecture doc
- [x] Enforce design patterns
