### ISSUE TITLE
Dashboard landing page

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#644]
#### Subtasks
- [x] UI Wireframe
- [x] Project Summary Endpoint 
- [x] List of Projects on Dashboard https://github.com/fastlane/ci/issues/655
- [x] Relative Pipe for the latest build Date #666
- [x] Status icon colors 🌈#698
- [x] Clickable Rows, Rows link to Project Details Page #687 
- [x] Add New Project Button #667
- [x] Add New Project Button leads to Add Project Dialog/Page #713 
- [ ] Icon for no builds
- [x] Loading spinner while loading data #668
- [ ] Global layout should include build-tag of current running version of ci (see https://github.com/fastlane/ci/issues/650)

#### Wireframe
![image](https://user-images.githubusercontent.com/2754461/38646489-0d53ff80-3d9d-11e8-84b4-a37dc42621cf.png)

**Comment by taquitos** [comment]
❤️ that you have Goat finder app. Can I get a beta invite?

**Comment by minuscorp** [comment]
> Relative Pipe for the latest build Date #666
![image](https://user-images.githubusercontent.com/3819883/38770104-c30f571c-400d-11e8-9b16-6a8db37e96e8.png)
