### ISSUE TITLE
Project Details Page

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#682]
#### Subtasks
- [x] UI Wireframe #685
- [x] Project Details Endpoint 
- [x] New Route for project #684
- [x] List of Builds on Project Details page #683
- [x] Link the commit shas to their github page #708 
- [x] Relative Pipe for the latest build Date #666
- [x] Status icon colors 🌈
- [x] Clickable Rows, Rows link to Build Details Page 
- [x] Loading spinner while loading data #668
- [x] Show project details
- [ ] Add Settings dialog #1060 
- [ ] loading indicator for Rebuild button
- [x] Add Rebuild option on hover
- [x] Get Branch and duration info
- [x] Switch to defined Status Icons

#### Mock
![image](https://user-images.githubusercontent.com/2754461/40148853-15b215c4-5925-11e8-963f-eb138b76c129.png)

**Comment by nakhbari** [comment]
Was thinking that we need some sort of notification that the build was triggered while we're waiting for a response on the rebuild. Maybe also add a notification if the build has already been triggered to rebuild, as to throttle the question and/or prevent accidental duplicate rebuilds? 

@chemichelle WDYT?
