### ISSUE TITLE
Build Details Page

### ISSUE THREAD

**Issue by minuscorp** [fastlane/ci#709]
##### UX
- [x] UI Wireframe #685

##### Backend
- [x] Build Details Endpoint #917 
- [x] Websocket endpoint for logs https://github.com/fastlane/ci/issues/890
- [ ] Websocket Logs are backfilled #1041
- [ ] Artifacts Endpoint #918 - blocked by #951 

##### Frontend
- [ ] Build logs formatting #1054
- [ ] Close websocket when getting `EOT` 
- [x] Connect to websocket from client #786
- [x] Display Build details
- [x] Display Logs in solarized dark color container
- [x] Display Artifacts
- [x] Display Build details
- [x] New Route for build #719 
- [x] Link the commit shas to their github page #708 
- [x] Relative Pipe for the latest build Date #666
- [x] Show error message on CI failure
- [x] Loading spinner while loading data #668

#### Mock
![image](https://user-images.githubusercontent.com/2754461/40148645-ee6f785e-5923-11e8-91d8-cfcc3a290258.png)
