### ISSUE TITLE
Add New Project Button leads to Add Project Dialog

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#713]
Parent Issue: #644 

#### Pre-requisite
- [x] Add button to create new project on dashboard #667

#### Work (can do data items before frontend)
- [x] Add Endpoint to `ProjectJsonController` which handles project post requests and creates a new project. #724
- [x] Add Endpoint to GET available Git repos
- [x] Add `DataService` method to POST new project. #750 
- [x] Add `DataService` method to GET all available repos. #716 
- [x] Endpoint that gets a project's lanes

#### Frontend
- [x] [Create Angular material Dialog](https://material.angular.io/components/dialog/overview)
- [x] [Add select and other form components](https://material.angular.io/components/select/overview)
- [x] throw in the dialog going to fullscreen on mobile
- [x] Add Tests
- [x] Wire the close buttons to close the dialog
- [x] Wire the add project button to add project
- [x] Enable the add project endpoint to just use the repo full name
- [x] Add form data validation and errors 
- [x] Get Lane data from backend
- [x] Gather form inputs and use the `DataService` post method to create the project
- [ ] Add Branch form
- [ ] Reload lanes when branch is changed
- [ ] Add invalid input styling

#### Wireframe
![image](https://user-images.githubusercontent.com/2754461/39064704-4aa6fbb0-4484-11e8-806c-f45b9bf1f5f3.png)

**Comment by nakhbari** [comment]
Gonna pick up the dialog frontend work.
