### ISSUE TITLE
Display server information and feedback

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#790]
We should show the server version in the Angular app. I was also thinking of making this a hub for things like feedback. I really like how Firebase did it.

#### Tasks
- [ ] Add a new component for this little box
- [ ] Add box in the app component in the corner
- [ ] Make component expand on click
- [ ] Add send feedback button in the expanded component

#### Quick mock
![image](https://user-images.githubusercontent.com/2754461/39484554-015b01a4-4d2b-11e8-8780-162a1cb5020a.png)

#### Firebase
![image](https://user-images.githubusercontent.com/2754461/39484353-6b7beb58-4d2a-11e8-927b-8aa539b4e4f1.png)
