### ISSUE TITLE
Create Toolbar component

### ISSUE THREAD

**Issue by nakhbari** [fastlane/ci#915]
Parent: #709 #682  

Toolbar component should be on the Project/Build page

#### Tasks
- [ ] Add Breadcrumbs
- [ ] Add transcludable area for settings
- [ ] Add transcludable area for actions 
- [ ] fastlane logo icon
- [ ] Styling

#### Mock
![image](https://user-images.githubusercontent.com/2754461/40396811-de881ed6-5de3-11e8-93da-b35f01c5244c.png)
